language: Swift
osx_image: xcode9.3
xcode_project: Utils.xcodeproj
xcode_scheme: Utils
before_install:
  - pod install --repo-update
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
