language: Swift
osx_image: xcode10
xcode_project: Utils/Utils.xcodeproj
xcode_scheme: Utils
before_install:
  - gem install xcpretty -N
  - brew install swiftlint || true
script:
  - set -o pipefail
  - cd Utils
  - xcodebuild test -scheme Utils -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty -c
